# English translations for nova_powervm.
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 6.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-03-19 18:06-0400\n"
"PO-Revision-Date: 2018-03-19 18:07-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=n != 1;"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.3\n"

#: nova_powervm/virt/powervm/driver.py:216
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Previsto un solo host; trovati %d"

#: nova_powervm/virt/powervm/driver.py:821
#, python-format
msgid ""
"The snapshot operation is not supported in conjunction with a "
"CONF.powervm.disk_driver setting of %s."
msgstr ""
"L'operazione di istantanea non è supportata in congiunzione con "
"un'impostazione CONF.powervm.disk_driver di %s."

#: nova_powervm/virt/powervm/driver.py:1023
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Collegamento vif non riuscito perché l'istanza %s non è stata trovata."

#: nova_powervm/virt/powervm/driver.py:1028
msgid "Plug vif failed because of an unexpected error."
msgstr "Collegamento vif non riuscito a causa di un errore imprevisto."

#: nova_powervm/virt/powervm/driver.py:1118
msgid "Cannot reduce disk size."
msgstr "Impossibile ridurre la dimensione del disco."

#: nova_powervm/virt/powervm/driver.py:1132
#: nova_powervm/virt/powervm/driver.py:1240
msgid "Cannot migrate local disks."
msgstr "Impossibile migrare i dischi locali."

#: nova_powervm/virt/powervm/driver.py:1757
#, python-format
msgid ""
"VNC based terminal for instance %(instance_name)s failed to open: "
"%(exc_msg)s"
msgstr ""
"L'apertura del terminale basato su VNC per l'istanza %(instance_name)s non è riuscita: "
"%(exc_msg)s"

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Impossibile individuare il gruppo di volumi %(vol_grp)s per memorizzarvi i supporti ottici"
"virtuali.  Impossibile creare il repository di supporti."

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"Avendo effettuato la scansione del bus SCSI %(bus)x sulla partizione di gestione, non è stato possibile rilevare "
"il disco con UDID %(udid)s dopo l'esecuzione di %(polls)d operazioni di polling nell'arco di %(timeout)d secondi."
"per l'istanza del servizio."

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Era previsto trovare un solo disco sulla partizione di gestione in "
"%(path_pattern)s; trovati %(count)d."

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"Il dispositivo %(devpath)s è ancora presente nella partizione dopo "
"il tentativo di eliminarlo.  Operazione di polling eseguita %(polls)d volte nell'arco di %(timeout)d"
"secondi."

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Impossibile associare il disco di avvio dell'istanza %(instance_name)s "
"alla partizione di gestione da qualsiasi Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Impossibile trovare l'associazione appena creata dell'elemento memoria %(stg_name)s"
" dal Virtual I/O Server %(vios_name)s alla partizione di gestione."

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Impossibile individuare il gruppo di volumi '%(vg_name)s' per questa operazione."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Impossibile individuare il cluster '%(clust_name)s' per questa operazione."

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "Impossibile individuare un cluster per questa operazione."

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"Sono stati trovati inaspettatamente %(clust_count)d cluster che corrispondono al nome"
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"Nessun cluster_name specificato.  Rifiutata la selezione di uno dei %(clust_count)d"
" cluster trovati."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossibile collegare la memoria (id: %(volume_id)s) alla macchina virtuale "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to extend volume (id: %(volume_id)s) on virtual machine "
"%(instance_name)s."
msgstr ""
"Impossibile estendere il volume (id: %(volume_id)s) sulla macchina virtuale "
"%(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossibile scollegare il volume (id: %(volume_id)s) dalla macchina virtuale "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Impossibile eseguire i passi preliminari della migrazione live sul volume (id: %(volume_id)s) "
"dalla macchina virtuale %(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "Impossibile completare l'API PowerVM per l'istanza=%(inst_name)s.%(reason)s"

#: nova_powervm/virt/powervm/exception.py:125
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a"
" VIOS to become active for %(wait_time)d seconds.  The compute agent is "
"not able to start if no Virtual I/O Servers are available.  Please check "
"the RMC connectivity between the PowerVM NovaLink and the Virtual I/O "
"Servers and then restart the Nova Compute Agent."
msgstr ""
"Non è disponibile alcun Virtual I/O Server.  Il driver ha provato ad attendere che un"
" VIOS diventasse disponibile per %(wait_time)d secondi.  L'agent di calcolo "
"non è in grado di avviarsi, se non sono disponibili VIOS (Virtual I/O Server).  Controllare "
"la connettività RMC tra PowerVM NovaLink e i Virtual I/O "
"Server, quindi, riavviare l'agent di calcolo Nova."

#: nova_powervm/virt/powervm/exception.py:134
msgid "There are no active Virtual I/O Servers available."
msgstr "Non sono disponibili Virtual I/O Server attivi."

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "Impossibile ricreare la macchina virtuale sul nuovo host.  L'errore è %(error)s"

#: nova_powervm/virt/powervm/exception.py:143
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"L'opzione %(then_opt)s è richiesta se %(if_opt)s è specificato come "
"'%(if_value)s'."

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "La migrazione live dell'istanza '%(name)s' non è riuscita per il motivo: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossibile migrare %(name)s, perché il volume %(volume)s non può essere collegato "
"all'host di destinazione %(host)s."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossibile migrare %(name)s perché l'host %(host)s consente solo %(allowed)s"
" migrazioni simultanee e attualmente sono in esecuzione %(running)s migrazioni."

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossibile migrare l'istanza '%(name)s' perché la dimensione dell'area di memoria "
"dell'origine (%(source_mrs)d MB) non corrisponde alla dimensione dell'area di memoria della "
"destinazione (%(target_mrs)d MB)."

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossibile migrare %(name)s, perché la sua modalità di compatibilità del processore %(mode)s "
" non è inclusa nell'elenco di modalità \"%(modes)s\" supportate dall'host di destinazione."

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"La migrazione live dell'istanza '%(name)s' non è riuscita perché lo stato della migrazione "
"è: %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:455
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"La migrazione live dell'istanza '%(name)s' non è riuscita perché non è pronta. "
"Motivo: %(reason)s"

#: nova_powervm/virt/powervm/vif.py:85
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "il parametro vif_type deve essere presente per questa implementazione di vif_driver"

#: nova_powervm/virt/powervm/vif.py:95
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s "
"on instance %(instance)s"
msgstr ""
"Impossibile trovare il driver PowerVM VIF appropriato per il tipo VIF %(vif_type)s "
"sull'istanza %(instance)s"

#: nova_powervm/virt/powervm/vif.py:540
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network "
"'%(physnet)s' for instance %(inst)s for SRIOV based VIF with MAC address "
"%(vif_mac)s."
msgstr ""
"Impossibile trovare porte Ethernet accettabili sulla rete fisica "
"'%(physnet)s' per l'istanza %(inst)s, per il VIF basato su SRIOV con indirizzo MAC "
"%(vif_mac)s."

#: nova_powervm/virt/powervm/vm.py:449
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Più pool di elaborazione condivisi con nome %(pool)s."

#: nova_powervm/virt/powervm/vm.py:453
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossibile trovare il pool di elaborazione condiviso %(pool)s"

#: nova_powervm/virt/powervm/vm.py:475
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"L'attributo versione %(attr)s deve essere True o False.  Il valore corrente "
"%(val)s non è consentito."

#: nova_powervm/virt/powervm/disk/driver.py:129
msgid "The configured disk driver does not support migration or resize."
msgstr "Il driver disco configurato non supporta la migrazione o il ridimensionamento."

#: nova_powervm/virt/powervm/disk/localdisk.py:300
msgid "Resizing file-backed instances is not currently supported."
msgstr "Il ridimensionamento delle istanze con backup su file non è attualmente supportato."

#: nova_powervm/virt/powervm/disk/ssp.py:119
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host "
"cluster: %(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"L'host non è un membro dello stesso cluster SSP. Il cluster dell'host "
"di origine: %(source_clust_name)s. SSP host di origine: %(source_ssp_name)s."

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossibile memorizzare NVRAM per l'istanza %(instance)s. Motivo:"
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossibile recuperare NVRAM per l'istanza %(instance)s. Motivo:"
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: "
"%(reason)s"
msgstr ""
"Impossibile eliminare NVRAM per l'istanza %(instance)s. Motivo:"
"%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "È necessario impostare l'opzione di configurazione '%(option)s'."

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "Impossibile memorizzare NVRAM dopo %d tentativi"

#: nova_powervm/virt/powervm/nvram/swift.py:272
msgid "Object does not exist in Swift."
msgstr "L'oggetto non esiste in Swift."

#: nova_powervm/virt/powervm/volume/__init__.py:65
#, python-format
msgid "Invalid connection type of %s"
msgstr "Tipo di connessione non valido di %s"

#: nova_powervm/virt/powervm/volume/npiv.py:522
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"Impossibile trovare un Virtual I/O Server che ospiti l'associazione porta NPIV per il "
"server."

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Impossibile rilevare un disco valido su qualsiasi Virtual I/O Server per il volume "
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O "
"Servers.  Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers,"
" but the disk was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"Impossibile rilevare l'hdisk sul numero richiesto di Virtual I/O  "
"Server.  Il volume %(volume_id)s richiedeva %(vios_req)d Virtual I/O Server,  "
" ma il disco è stato trovato solo su %(vios_act)d Virtual I/O Server."


# ENGL1SH_VERS10N 62006_10 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC141AAP001 1
